console.log('CHALLENGE 1' + '\n');
const heightMark = 1.69;
const weightMark = 78;
const heightJohn = 1.95;
const weightJohn = 92;
const BMIMark = weightMark / (heightMark ** 2);
const BMIJohn = weightJohn / (heightJohn ** 2);
console.log(BMIJohn, BMIMark);
const markHigherBMI = BMIMark > BMIJohn;
console.log(markHigherBMI);
